spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LikeSimple/spring-cloud-config #default Config Server Uri
          search-paths: repos
      label: ${spring.profiles.active}
  rabbitmq:
    username: rabbit
    password: 123456
eureka:
  instance:
    prefer-ip-address: true
    #    lease-renewal-interval-in-seconds: 5
    #    lease-expiration-duration-in-seconds: 20
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
#    registry-fetch-interval-seconds: 10
server:
  port: 9010
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS