spring:
  application:
    name: service-config
  profiles:
    active: dev

---
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LikeSimple/spring-cloud-config #default Config Server Uri
          search-paths: repos
      label: ${spring.profiles.active}
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    registry-fetch-interval-seconds: 10
server:
  port: 9010