spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LikeSimple/spring-cloud-config #default Config Server Uri
          search-paths: repos
      label: master
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    registry-fetch-interval-seconds: 10