spring:
  application:
    name: vault-server
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    registry-fetch-interval-seconds: 10
cloud:
  vault:
    token: 9a63de21-8af7-311a-9a5a-151b6a0d4795
    scheme: http
